In [2]:
import os, sys
import numpy as np
from sklearn.metrics import pairwise_distances

In [3]:
X = np.array([
    [1, 3, 4, 5],
    [4, 1, 5, 9],
    [0, 5, 5, 5],
])

distances = [
    pairwise_distances(X, X, metric='l1'),
    pairwise_distances(X, X, metric='l2'),
    pairwise_distances(X, X, metric='cosine'),
]

for m in distances:
    print(" & ".join([' ']+[f'cell {i+1}' for i in range(len(m))]) + "\\\\")
    for i, row in enumerate(m):
        line = f"cell {i+1} & " + " & ".join([f'{v:.3f}' for v in row])+ '\\\\'
        print(line)
    print('')

  & cell 1 & cell 2 & cell 3\\
cell 1 & 0.000 & 10.000 & 4.000\\
cell 2 & 10.000 & 0.000 & 12.000\\
cell 3 & 4.000 & 12.000 & 0.000\\

  & cell 1 & cell 2 & cell 3\\
cell 1 & 0.000 & 5.477 & 2.449\\
cell 2 & 5.477 & 0.000 & 6.928\\
cell 3 & 2.449 & 6.928 & 0.000\\

  & cell 1 & cell 2 & cell 3\\
cell 1 & 0.000 & 0.091 & 0.030\\
cell 2 & 0.091 & 0.000 & 0.219\\
cell 3 & 0.030 & 0.219 & 0.000\\



In [6]:
vecs = []
np.random.seed(12345)
l = 5
for i in range(25):
    v = []
    for j in range(l):
        v.append(np.random.random())
    vecs.append(v)

vecs = np.array(vecs)
print(vecs[:5])

d = pairwise_distances(vecs, metric='cosine')

vecs += 1
print(vecs[:5])


d2 = pairwise_distances(vecs, metric='cosine')

[[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503]
 [0.5955447  0.96451452 0.6531771  0.74890664 0.65356987]
 [0.74771481 0.96130674 0.0083883  0.10644438 0.29870371]
 [0.65641118 0.80981255 0.87217591 0.9646476  0.72368535]
 [0.64247533 0.71745362 0.46759901 0.32558468 0.43964461]]
[[1.92961609 1.31637555 1.18391881 1.20456028 1.56772503]
 [1.5955447  1.96451452 1.6531771  1.74890664 1.65356987]
 [1.74771481 1.96130674 1.0083883  1.10644438 1.29870371]
 [1.65641118 1.80981255 1.87217591 1.9646476  1.72368535]
 [1.64247533 1.71745362 1.46759901 1.32558468 1.43964461]]


In [7]:
[t for t in zip(d[0], d2[0])][:10]

[(0.0, 0.0),
 (0.2161703134669103, 0.02823180175865414),
 (0.18840793012105594, 0.026012125917114548),
 (0.2290515387755494, 0.030591144793486125),
 (0.12599623621726086, 0.015109120638919338),
 (0.2734378275576941, 0.039625245407803655),
 (0.5212764920915556, 0.07292699420535653),
 (0.21557904249737558, 0.0297449889470619),
 (0.18754512538582613, 0.025098711919579464),
 (0.39338929045962134, 0.04525680182145653)]

In [41]:
import plotly
import plotly.subplots as sp
from plotly import graph_objects as go
import numpy as np

axis_col = 'rgba(0, 0, 0, 0.15)'
zero_col = 'rgba(0, 0, 0, 0.3)'
no_col = 'rgba(0, 0, 0, 0)'
axis_desc: dict = dict(linecolor=no_col, gridcolor=axis_col, zerolinecolor=zero_col, zerolinewidth=2, range=[-1.1, 1.1])
layout = dict(
    autosize=False,
    width=680,
    height=600,
    margin=dict(
        l=60, r=25, b=60, t=25, pad=5
    ),
    # paper_bgcolor="white",
    font_family="Times New Roman",
    font_color="black",
    font_size=20,
    plot_bgcolor='white',
    xaxis=axis_desc,
    yaxis=axis_desc, #dict(**axis_desc, title=""),#, scaleanchor="x1", scaleratio=1),
    xaxis2=axis_desc,
    yaxis2=axis_desc, #dict(**axis_desc, scaleanchor="x2", scaleratio=1),
)

def l_p(x, p):
    return (1-abs(x)**p)**(1/p)

def gen_range(a, b, k):
    step = (b-a)/k
    return np.arange(a, b+step, step)

resolution = 999
_half_x = gen_range(-1, 1, resolution)
xs = np.hstack([_half_x, _half_x[::-1]])

fig = go.Figure(data=[
    go.Scatter(
        x=[-1, -1, 1, 1, 1, 1, -1, -1],y=[0, 1, 1, 0, 0, -1, -1, 0],
        mode="lines",
        name=f"inf",
    ),
]+[
    go.Scatter(
        x=xs, y=[l_p(x, p) if i < (resolution+2) else -l_p(x, p) for i, x in enumerate(xs)],
        mode="lines",
        name=f"{p}",
    )
for p in [3, 2, 1.5, 1]], layout=layout)
fig.show()

/tmp/ipykernel_367902/605985715.py:29: RuntimeWarning:

invalid value encountered in double_scalars



In [36]:
len(xs)

2002

In [9]:
np.arange(-1, 1, 0.01)

array([-1.0000000e+00, -9.9000000e-01, -9.8000000e-01, -9.7000000e-01,
       -9.6000000e-01, -9.5000000e-01, -9.4000000e-01, -9.3000000e-01,
       -9.2000000e-01, -9.1000000e-01, -9.0000000e-01, -8.9000000e-01,
       -8.8000000e-01, -8.7000000e-01, -8.6000000e-01, -8.5000000e-01,
       -8.4000000e-01, -8.3000000e-01, -8.2000000e-01, -8.1000000e-01,
       -8.0000000e-01, -7.9000000e-01, -7.8000000e-01, -7.7000000e-01,
       -7.6000000e-01, -7.5000000e-01, -7.4000000e-01, -7.3000000e-01,
       -7.2000000e-01, -7.1000000e-01, -7.0000000e-01, -6.9000000e-01,
       -6.8000000e-01, -6.7000000e-01, -6.6000000e-01, -6.5000000e-01,
       -6.4000000e-01, -6.3000000e-01, -6.2000000e-01, -6.1000000e-01,
       -6.0000000e-01, -5.9000000e-01, -5.8000000e-01, -5.7000000e-01,
       -5.6000000e-01, -5.5000000e-01, -5.4000000e-01, -5.3000000e-01,
       -5.2000000e-01, -5.1000000e-01, -5.0000000e-01, -4.9000000e-01,
       -4.8000000e-01, -4.7000000e-01, -4.6000000e-01, -4.5000000e-01,
      