In [1]:
import scipy
import numpy as np



In [2]:
def project(a: np.ndarray, b:np.ndarray):
    len_b = np.linalg.norm(b)
    return a.T@b/len_b**2*b

a = np.array([1, 3, 2])
b = np.array([1, 2, 3])
c = np.array([3, 1, 2])

project(a, b), project(a, c)

(array([0.92857143, 1.85714286, 2.78571429]),
 array([2.14285714, 0.71428571, 1.42857143]))

In [12]:
# returns closest vector to @v within given space
def orthogonal_projection(v: np.ndarray, space: np.ndarray):
    P = space.T @ np.linalg.inv(space@space.T) @ space
    return P@v

A = np.array([
    [1, 2, 3],
    [3, 1, 2],
])
a = np.array([1, 3, 2])

d = orthogonal_projection(a, A)
# not inverible!
d

array([0.84, 1.88, 2.8 ])

In [9]:
orthogonal_projection(a, c)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional